Upstream/fix feat proj params
Autoware-AI/core_perception pull request #20
Opened 2020-10-09 20:33 UTC by icolwell-as

Transferred from GitLab. See original PR for details:

https://gitlab.com/autowarefoundation/autoware.ai/core_perception/-/merge_requests/79

2020-10-28 16:03 UTC, LiyouZhou requested changes
I can see what you did here. but for the sake of clear history and documentation, would you mind adding some details in the commit message about why this change is made.

see https://chris.beams.io/posts/git-commit/#why-not-how for some tips on commit messages.

2020-10-28 16:03 UTC, LiyouZhou commented on trafficlight_recognizer/launch/feat_proj.launch
> -
This line change is no necessary, would prefer if this change is not in this PR.

2020-10-28 16:05 UTC, LiyouZhou commented
@icolwell-as looks like all your PRs only contain a link to another PR which also does not contain too much info either. Would you mind just populating the commit messages and PR bodys with a bit more detail. This would help me greatly in review. Thank you very much.

2020-10-29 19:39 UTC, icolwell-as commented
@LiyouZhou, my apologies for the sometimes sparse PR explanations. Some of these PRs are left over from when Autoware.AI was transferred from gitlab to github hence the link to other PRs. The rest of the PRs are transferred from our gitlab fork and include links back to the original MR which contains descriptions of the changes and links to issues that the MR is resolving, there are also code review discussions which may help you understand some of the code.

Re-writing the commit history of all these commits will be very time consuming, but improving the PR descriptions is more feasible if that is acceptable to you. Are there some specific PRs that are the most confusing that you would like me to start with?

2020-11-06 16:07 UTC, icolwell-as commented
@JWhitleyWork, reminder to re-open (assuming you closed to trigger a re-build).

2020-11-06 16:34 UTC, JWhitleyWork commented
@icolwell-as Sorry about that. It got automatically closed due to the issue number being mentioned in a commit message. This PR looks perfectly fine to me. I'll merge once CI passes.

2020-11-06 17:37 UTC, JWhitleyWork approved these changes

2020-11-06 17:37 UTC, merged